# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rider' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Rider
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'


  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  target 'RiderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Rider-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Rider-tvOS

  target 'Rider-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
