export const LOGIN = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";
export const ERROR = "ERROR";
export const REQUEST_FACEBOOK_LOGIN = "REQUEST_FACEBOOK_LOGIN";
export const REQUEST_FACEBOOK_LOGIN_FAILURE = "REQUEST_FACEBOOK_LOGIN_FAILURE";
