export default {
  fb_icon: require("../assets/icons/fb_icon.png"),
  right_arrow: require("../assets/icons/right_arrow.png"),
  current_location: require("../assets/icons/current_location.png"),
  search: require("../assets/icons/search.png"),
  car_time: require("../assets/icons/car_time.png"),
  cancel: require("../assets/icons/cancel.png"),
  file_icon: require("../assets/icons/file_icon.png"),
  recent_icon: require("../assets/icons/recent_icon.png"),
  location_icon: require("../assets/icons/location_icon.png"),
  home_icon: require("../assets/icons/home_icon.png"),
  add_icon: require("../assets/icons/add_icon.png"),
  drawer_menu: require("../assets/icons/drawer_menu.png"),
  help: require("../assets/icons/help.png"),
  heart: require("../assets/icons/heart.png"),
  history: require("../assets/icons/history.png"),
  Home: require("../assets/icons/Home.png"),
  notification: require("../assets/icons/notification.png"),
  logout: require("../assets/icons/logout.png"),
  refer: require("../assets/icons/refer.png")
};
